---
- name: Create user and group
  hosts: all
  gather_facts: false
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: create group test
      group:
        name: boogroup
        state: absent

    - name: create user boopathy
      user:
        name: boopathy
        password: "{{ 'Open@123' | password_hash('sha512') }}"
        state: absent
        group: boogroup
        groups: boogroup
